### ISSUE TITLE
Help us test: new things.py release 0.0.15

### ISSUE THREAD

**Issue by mikez** [thingsapi/things.py#113]
As of fixing all issues in #110, we're ready for a new release.

I propose we push to PyPI immediately (since its breaking already), and then invite various people to test it. (/cc @AlexanderWillner)

**Comment by mikez** [comment]
# Context

## What changed
- Various things broke with the new Things database that were fixed (see #110).
- The values for date-parameters were extended; now you can do this:

```pycon
>>> things.todos(stop_date="2023-05-21", status="completed")
>>> things.todos(deadline="<2024-01-01")
>>> things.todos(start_date=">2023-01-01")
```

## How you can help

1. Test your workflows and ensure everything appears and works as expected.
2. Test various methods of the API: https://thingsapi.github.io/things.py/things/api.html
3. Read the documentation and ask if something seems unclear.

## Gratitude ☀️

Besides @CaAlden, @NickChristensen,  @hlipnick, @subokita, @bkleinen mentioned already, who played an important part in this update... also kudos to @jeredactyl, @patrick91, @fabge, @ishan1m, @roelvangils, @nathankoerschner, @chrizel, @Avery2, and @lmgibson who have supported this library directly or indirectly. Your participation makes open source work.

Thank you. 🙏

**Comment by ishan1m** [comment]
Thank you so much 🙏

(This might just be something specific to my environment, but after upgrading things-cli, I still get an error. Am I doing something wrong?)
![Screenshot 2023-05-22 at 18 11 24@2x](https://github.com/thingsapi/things.py/assets/107513942/8aa350bb-8a24-464c-a3f3-26ea99a2335c)

**Comment by AlexanderWillner** [comment]
> Am I doing something wrong?

The dependency (`things.py`) was not updated automatically. This might be fixed in `things-cli` v0.2.1

**Comment by mikez** [comment]
@ishan1m if you run `pip3 install --upgrade things-cli` that third-party library might work now (its author submitted a fix thanks to your comment).
